workflows:
  android-app:
    name: Build MaoriDict APK
    environment:
      vars:
        PACKAGE_NAME: "com.example.maoridict"
      flutter: false
      xcode: none
      java: 17
      image: ubuntu-latest

    scripts:
      - name: Set up Gradle wrapper
        script: |
          chmod +x ./gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Build debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - geoffthetechnical@gmail.com
